CREATE SCHEMA IF NOT EXISTS esquadritec;

set schema 'esquadritec';

CREATE TABLE IF NOT EXISTS ENDERECO(
    ID SERIAL PRIMARY KEY NOT NULL,
    CIDADE varchar(30) NOT NULL,
    RUA varchar(30) NOT NULL,
    BAIRRO varchar(30) NOT NULL,
    NUMERO varchar(30) NOT NULL,
    OBSERVACAO varchar(30) NOT NULL    
);

CREATE TABLE IF NOT EXISTS CLIENTE(
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME varchar(30) NOT NULL,
    CPF varchar(30) NOT NULL,
    CNPJ varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    ENDERECO INT,
    FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TELEFONE(
    ID SERIAL PRIMARY KEY NOT NULL,
    TELEFONE varchar(30) NOT NULL,
    CLIENTE INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORCAMENTO(
    ID SERIAL PRIMARY KEY NOT NULL,
    OBSERVACAO varchar(100),
    DESCONTO int,
    STATUS varchar(30),
    VALOR_T_B float NOT NULL,
    VALOR_F float NOT NULL,
    DATA date NOT NULL,
    CLIENTE int NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME varchar(30) NOT NULL,
    SENHA varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    DATA varchar(30) NOT NULL,
    ADMIN boolean NOT NULL 
);

CREATE TABLE IF NOT EXISTS ATENDIMENTO(
    ID SERIAL PRIMARY KEY NOT NULL,
    USUARIO INT NOT NULL,
    CLIENTE INT NOT NULL,
    ORCAMENTO INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LINHA(
    ID SERIAL PRIMARY KEY NOT NULL,
    LINHA varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELO(
    ID SERIAL PRIMARY KEY NOT NULL,
    MODELO varchar(30) NOT NULL

);

CREATE TABLE IF NOT EXISTS PRODUTO(
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR float NOT NULL,
    ORCAMENTO int NOT NULL,
    MODELO int NOT NULL,
    LINHA int NOT NULL,
    FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (MODELO) REFERENCES MODELO(ID) ON DELETE CASCADE,
    FOREIGN KEY (LINHA) REFERENCES LINHA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MATERIAIS(
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR float NOT NULL
);

CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA(
    ID SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MATERIAL_PRODUTO(
    ID SERIAL PRIMARY KEY NOT NULL,
    VALOR float NOT NULL,
    QUANTIDADE float NOT NULL,
    UNIDADE_MEDIDA int NOT NULL,
    PRODUTO int NOT NULL,
    MATERIAIS int NOT NULL,
    FOREIGN KEY (MATERIAIS) REFERENCES MATERIAIS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID) ON DELETE CASCADE
);

INSERT INTO usuario(nome, email, senha, data, admin) values('admin',  'admin', 'MjAyMS0wMy0wNSAxMTowN2FkbWlu', '2021-03-05 11:07', TRUE);


CREATE OR REPLACE FUNCTION VALOR_UPDATE()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN
            UPDATE PRODUTO SET VALOR = PRODUTO.VALOR + (NEW.VALOR * NEW.QUANTIDADE) WHERE PRODUTO.ID = NEW.PRODUTO;
            return NEW;
    END;
    $function$
;
CREATE TRIGGER VALOR AFTER INSERT OR UPDATE ON MATERIAL_PRODUTO
    FOR EACH ROW EXECUTE PROCEDURE VALOR_UPDATE();



CREATE OR REPLACE FUNCTION ORCAMENTO_UPDATE()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE VALOR INTEGER;
    BEGIN
			SELECT SUM(PRODUTO.VALOR) INTO VALOR FROM PRODUTO WHERE PRODUTO.ORCAMENTO = NEW.ORCAMENTO;
			UPDATE ORCAMENTO SET VALOR_T_B = VALOR WHERE ORCAMENTO.ID = NEW.ORCAMENTO;
			UPDATE ORCAMENTO SET VALOR_F = (VALOR - (VALOR * (ORCAMENTO.DESCONTO / 100))) WHERE ORCAMENTO.ID = NEW.ORCAMENTO;
            return NEW;
    END;
    $function$
;
CREATE TRIGGER VALOR_ORCAMENTO AFTER INSERT OR UPDATE ON PRODUTO
    FOR EACH ROW EXECUTE PROCEDURE ORCAMENTO_UPDATE();
