CREATE TABLE TELEFONE(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TELEFONE varchar(30) NOT NULL,
    CLIENTE int NOT NULL
);

CREATE TABLE CLIENTE(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    CPF varchar(30) NOT NULL,
    CNPJ varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL    
);

CREATE TABLE ENDERECO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CIDADE varchar(30) NOT NULL,
    RUA varchar(30) NOT NULL,
    BAIRRO varchar(30) NOT NULL,
    NUMERO varchar(30) NOT NULL,
    OBSERVACAO varchar(30) NOT NULL    
);

CREATE TABLE ORCAMENTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CLIENTE int NOT NULL,
    OBSERVACAO varchar(100) NOT NULL,
    DESCONTO int,
    STATUS varchar(30),
    VALOR_T_B double NOT NULL,
    VALOR_F double NOT NULL,
    DATA date NOT NULL   
);

CREATE TABLE ATENDIMENTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USUARIO int NOT NULL,
    CLIENTE int NOT NULL,
    ORCAMENTO int NOT NULL
);

CREATE TABLE USUARIO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    SENHA varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    ADMIN boolean NOT NULL 
);

CREATE TABLE LINHA(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    LINHA varchar(30) NOT NULL
);

CREATE TABLE PRODUTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ORCAMENTO int NOT NULL,
    MODELO int NOT NULL,
    LINHA int NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR varchar(30) NOT NULL
);

CREATE TABLE MODELO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MODELO varchar(30) NOT NULL

);

CREATE TABLE MATERIAL_PRODUTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRODUTO int NOT NULL,
    MATERIAIS int NOT NULL,
    QUANTIDADE int NOT NULL,
    VALOR boolean NOT NULL 
);

CREATE TABLE MATERIAIS(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR varchar(30) NOT NULL
);

ALTER TABLE TELEFONE ADD CONSTRAINT CLIENTE_FK_1 FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE ORCAMENTO ADD CONSTRAINT CLIENTE_FK_2 FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE ATENDIMENTO ADD CONSTRAINT USUARIO_FK_1 FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID);
ALTER TABLE ATENDIMENTO ADD CONSTRAINT CLIENTE_FK_3 FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID);
ALTER TABLE ATENDIMENTO ADD CONSTRAINT ORCAMENTO_FK_1 FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT ORCAMENTO_FK_2 FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT MODELO_FK_1 FOREIGN KEY (MODELO) REFERENCES MODELO (ID);
ALTER TABLE PRODUTO ADD CONSTRAINT LINHA_FK_1 FOREIGN KEY (LINHA) REFERENCES LINHA (ID);
ALTER TABLE MATERIAL_PRODUTO ADD CONSTRAINT PRODUTO_FK_1 FOREIGN KEY (PRODUTO) REFERENCES PRODUTO (ID);
ALTER TABLE MATERIAL_PRODUTO ADD CONSTRAINT MATERIAIS_FK_1 FOREIGN KEY (MATERIAIS) REFERENCES MATERIAIS (ID);
ALTER TABLE MATERIAL_PRODUTO ADD CONSTRAINT PRODUTO_FK_2 FOREIGN KEY (PRODUTO) REFERENCES PRODUTO (ID);
ALTER TABLE MATERIAL_PRODUTO ADD CONSTRAINT MATERIAIS_FK_2 FOREIGN KEY (MATERIAIS) REFERENCES MATERIAIS (ID);
