CREATE SCHEMA IF NOT EXISTS esquadritec;

USE esquadritec;

CREATE TABLE IF NOT EXISTS ENDERECO(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CIDADE varchar(30) NOT NULL,
    RUA varchar(30) NOT NULL,
    BAIRRO varchar(30) NOT NULL,
    NUMERO varchar(30) NOT NULL,
    OBSERVACAO varchar(30) NOT NULL    
);

CREATE TABLE IF NOT EXISTS CLIENTE(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    CPF varchar(30) NOT NULL,
    CNPJ varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    ENDERECO INT,
    FOREIGN KEY (ENDERECO) REFERENCES ENDERECO(ID)
);

CREATE TABLE IF NOT EXISTS TELEFONE(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TELEFONE varchar(30) NOT NULL,
    CLIENTE INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE IF NOT EXISTS ORCAMENTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    OBSERVACAO varchar(100),
    DESCONTO int,
    STATUS varchar(30),
    VALOR_T_B double NOT NULL,
    VALOR_F double NOT NULL,
    DATA date NOT NULL,
    CLIENTE int NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    SENHA varchar(30) NOT NULL,
    EMAIL varchar(30) NOT NULL,
    ADMIN boolean NOT NULL 
);

CREATE TABLE IF NOT EXISTS ATENDIMENTO(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USUARIO INT NOT NULL,
    CLIENTE INT NOT NULL,
    ORCAMENTO INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO(ID),
    FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IF NOT EXISTS LINHA(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    LINHA varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODELO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MODELO varchar(30) NOT NULL

);

CREATE TABLE IF NOT EXISTS PRODUTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR DOUBLE NOT NULL,
    ORCAMENTO int NOT NULL,
    MODELO int NOT NULL,
    LINHA int NOT NULL,
    FOREIGN KEY (ORCAMENTO) REFERENCES ORCAMENTO(ID),
    FOREIGN KEY (MODELO) REFERENCES MODELO(ID),
    FOREIGN KEY (LINHA) REFERENCES LINHA(ID)
);

CREATE TABLE IF NOT EXISTS MATERIAIS(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME varchar(30) NOT NULL,
    VALOR DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS UNIDADE_MEDIDA(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MATERIAL_PRODUTO(
    ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    VALOR DOUBLE NOT NULL,
    QUANTIDADE DOUBLE NOT NULL,
    UNIDADE_MEDIDA int NOT NULL,
    PRODUTO int NOT NULL,
    MATERIAIS int NOT NULL,
    FOREIGN KEY (MATERIAIS) REFERENCES MATERIAIS(ID),
    FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID)
);

INSERT INTO usuario(nome, email, senha) values('admin',  'admin', 'MWFkbWlu')

DELIMITER //
CREATE TRIGGER VALOR AFTER INSERT ON MATERIAL_PRODUTO
FOR EACH ROW BEGIN
    UPDATE PRODUTO SET VALOR = PRODUTO.VALOR + (NEW.VALOR * NEW.QUANTIDADE) WHERE PRODUTO.ID = NEW.PRODUTO;
END;
//

DELIMITER //
CREATE TRIGGER VALOR_ORCAMENTO AFTER UPDATE ON PRODUTO
FOR EACH ROW BEGIN
	DECLARE VALOR INTEGER;
    SELECT SUM(P.VALOR) INTO VALOR FROM PRODUTO P WHERE P.ORCAMENTO = NEW.ORCAMENTO;
	UPDATE ORCAMENTO SET VALOR_T_B = VALOR WHERE ORCAMENTO.ID = NEW.ORCAMENTO;
    UPDATE ORCAMENTO SET VALOR_F = (VALOR - (VALOR * (ORCAMENTO.DESCONTO / 100))) WHERE ORCAMENTO.ID = NEW.ORCAMENTO;
END;
//
